### ISSUE TITLE
The critical crash

### ISSUE THREAD

**Issue by harleyguru** [kumarharsh/graphql-for-vscode#110]
When I open .gql file in root directory, I get this error:
```
[Info  - 20:19:43] NODE_PATH value is: /Users/anatolii/.nvm/versions/node/v8.10.0/lib
[Info  - 20:19:43] Module '@playlyfe/gql' loaded from: /Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/index.js
[vscode] File extensions registered:  [ 'gql', 'js' ]
[Watch established (gqlSchemaFiles)] 
	basePath: /Volumes/Data/Workspace/Backend/Serverless/Hiregoat/hiregoat-backend 
	RelativePath: undefined 
	Files: "**/*.gql"
[Watch established (gqlQueryFiles-1)] 
	basePath: /Volumes/Data/Workspace/Backend/Serverless/Hiregoat/hiregoat-backend 
	RelativePath: undefined 
	Files: "**/*.gql"
[Watch established (gqlQueryFiles-0)] 
	basePath: /Volumes/Data/Workspace/Backend/Serverless/Hiregoat/hiregoat-backend 
	RelativePath: undefined 
	Files: "**/*.js"
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at QueryManager._parseFile (/Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/query/QueryManager.js:181:32)
    at /Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/query/QueryManager.js:141:54
    at Array.forEach (native)
    at QueryManager._updateFiles (/Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/query/QueryManager.js:133:13)
    at /Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/query/QueryManager.js:99:17
    at onChange (/Users/anatolii/.nvm/versions/node/v8.10.0/lib/node_modules/@playlyfe/gql/lib/query/QueryManager.js:90:30)
[Info  - 20:19:46] Connection to server got closed. Server will restart.
[Info  - 20:19:46] The graphql server has stopped running
```

This was working well for some months, but after I restart my mac, it has been broken..
Watchman & @playlyfe/gql have been installed successfully and confirmed they are working successfully.

After I install @playlyfe/gql package via nvm/npm, this is happening.

**Comment by kumarharsh** [comment]
Which version of `@playlyfe/gql` do you have installed currently?

**Comment by harleyguru** [comment]
@kumarharsh First off, thanks for your quick response.
I've fixed the issue, it's strange.
Same .gqlconfig was working earlier, but it didn't work any more this time.
So I've removed js parsing config from it.
Then it worked.
You can close it.

**Comment by kumarharsh** [comment]
I'm closing this issue, let me know if you face this again.
