### ISSUE TITLE
The Graphql For VSCode server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by jvbianchi** [kumarharsh/graphql-for-vscode#29]
If I run `watchman -v` I get the response `4.7.0`

Every time I open VSCode I got this error, with this output:
```
[Info  - 4:12:00 PM] NODE_PATH value is: /Users/user/Developer/app
[Info  - 4:12:05 PM] Module '@playlyfe/gql' loaded from: /Users/user/Developer/app/node_modules/@playlyfe/gql/lib/index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 4:12:05 PM] Connection to server got closed. Server will restart.
[Info  - 4:12:05 PM] The graphql server has stopped running
[Info  - 4:12:06 PM] NODE_PATH value is: /Users/user/Developer/app
[Info  - 4:12:07 PM] Module '@playlyfe/gql' loaded from: /Users/user/Developer/app/node_modules/@playlyfe/gql/lib/index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 4:12:07 PM] Connection to server got closed. Server will restart.
[Info  - 4:12:07 PM] The graphql server has stopped running
[Info  - 4:12:07 PM] NODE_PATH value is: /Users/user/Developer/app
[Info  - 4:12:08 PM] Module '@playlyfe/gql' loaded from: /Users/user/Developer/app/node_modules/@playlyfe/gql/lib/index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 4:12:08 PM] Connection to server got closed. Server will restart.
[Info  - 4:12:08 PM] The graphql server has stopped running
[Info  - 4:12:08 PM] NODE_PATH value is: /Users/user/Developer/app
[Info  - 4:12:08 PM] Module '@playlyfe/gql' loaded from: /Users/user/Developer/app/node_modules/@playlyfe/gql/lib/index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 4:12:08 PM] Connection to server got closed. Server will restart.
[Info  - 4:12:08 PM] The graphql server has stopped running
[Info  - 4:12:09 PM] NODE_PATH value is: /Users/user/Developer/app
[Info  - 4:12:09 PM] Module '@playlyfe/gql' loaded from: /Users/user/Developer/app/node_modules/@playlyfe/gql/lib/index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 4:12:09 PM] Connection to server got closed. Server will not be restarted.
[Info  - 4:12:09 PM] The graphql server has stopped running

```

**After I reload VSCode the problem goes away.**

**Comment by kumarharsh** [comment]
Are you on Windows?

**Comment by jvbianchi** [comment]
macOS Sierra 10.12.5

**Comment by kumarharsh** [comment]
Okay. I asked because it also crashes sometimes for me, On Windows, it happens because watchman watches the whole directory (down to the last node_module), and if I'm running any other command which might lock-up the directories while watchman is initializing, it fails with a similar error. In that case, I run 'watchman shutdown-server' and start vscode again (or just reload the window).

I'm not exactly sure yet why it's happening for you. But giving a path error is weird - were you running some `npm install` or brew install while vscode was opening?

**Comment by jvbianchi** [comment]
no, I start the computer and open VSCode and this error happens every time

**Comment by wttw** [comment]
If you start an app on OS X from the dock you get the system environment, including the system PATH (mostly set from config files in /etc/paths.d, AFAICT). If you start it from a command line (e.g. with "code .") you get the environment set in your shell.

A lot of weird OS X problems with VS Code seem to come from it being started with the wrong PATH; this looks like one of those.

**Comment by jvbianchi** [comment]
Is there a way to solve this path problem?

**Comment by kumarharsh** [comment]
@wttw thanks. @jvbianchi  yes, I also think this is related to the same problem - I remember there was a long issue on vscode repo relating to this, with the recommended fix for it. I'll update this when I find that issue.

**Comment by kumarharsh** [comment]
@jvbianchi did you get this solved? I'm sure I remember the issue being discussed in the VSCode or Atom repos about the path problems being linked to where the editor was launched from, but haven't been able to find the exact issue, but here are some more discussions along those lines:

https://github.com/Microsoft/vscode/issues/17798
https://github.com/Microsoft/vscode/issues/14229
https://github.com/atom/atom/issues/6956

I'm closing this issue as it's out of scope for this plugin, and more of an editor issue. Please reopen if you feel otherwise.
