### ISSUE TITLE
The Graphql For VSCode server crashed 5 times in the last 3 minutes. The server will not be restarted. : Watchman was not found in PATH

### ISSUE THREAD

**Issue by the-simian** [kumarharsh/graphql-for-vscode#47]
The Graphql For VSCode server crashed 5 times in the last 3 minutes. The server will not be restarted. : Watchman was not found in PATH
```
Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 1:57:03 PM] Connection to server got closed. Server will restart.
[Info  - 1:57:03 PM] The graphql server has stopped running
[Info  - 1:57:03 PM] NODE_PATH value is: e:\Users\Simian\Desktop\trigram\lifeguides-web
[Info  - 1:57:04 PM] Module '@playlyfe/gql' loaded from: e:\Users\Simian\Desktop\trigram\lifeguides-web\node_modules\@playlyfe\gql\lib\index.js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:163
```
![image](https://user-images.githubusercontent.com/954596/31057939-e23e3e88-a6b0-11e7-91bc-6d30f21e4cff.png)

- Watchman IS in my path. I can call it from cmd line, no problem.

![image](https://user-images.githubusercontent.com/954596/31058098-87a9ed84-a6b3-11e7-964b-1ec78b180f7c.png)

- I am using Windows

**Comment by kumarharsh** [comment]
Yes, that's a valid issue. There are times when the vscode plugin doesn't communicate with watchman which is running on Windows. The trick is to first do `watchman shutdown-server`, and then just reload your vscode window via `Reload Window` which will cause the plugin to get reinitialized, and things should work.

I've myself faced this issue several times, and it's really irritating on Windows (watchman still doesn't work well on Windows...). We are tracking an issue to removing watchman altogether in #42.

**Comment by jalalmanafi** [comment]
Same problem , can anyone helps me ?

**Comment by ikramhasib007** [comment]
If you have any client-side schema then add them into `apollo.config.js` file too. like

```
module.exports = {
  client: {
    includes: ['./src/stores/schema.js'],
    service: {
      name: 'com merchant',
      service: 'com-merchant',
      url: 'http://localhost:3003/graphql'
    }
  }
};
```

schema.js
```
import { gql } from '@apollo/client'

export const typeDefs = gql`
  extend type Query {
    _searchQuery: String!
    _checkout: Checkout!
  }
`
```

**Comment by GBrachetta** [comment]
I have the same issue and I'm on a Mac. Don't understand why this has been closed. It happens every single time to me.

**Comment by apetta** [comment]
Getting this every time on Mac M1 mini

**Comment by simon-abbott** [comment]
Also on mac here, extension v0.4.4 works perfectly, but as soon as I update to v0.4.6 it breaks. I was able to workaround this by going into the extension and downgrading to 0.4.4 (go to the extension, click the down arrow next to "uninstall", choose "Install another version", and select 0.4.4).

**Comment by adamduren** [comment]
@kumarharsh being that this has been liked and watched 43 times in the last five days it seems like a valid issue although possibly should be a new one as at least in my case it doesn't appear to be related to Watchman but due to the fact there is not a valid graphQL schema file in some of my non-graphQL projects.

```
6/2/2022, 4:07:41 PM [3] (pid: 2846) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
6/2/2022, 4:07:41 PM [2] (pid: 2846) graphql-language-service-usage-logs: e: GraphQL Config file is not available in the provided config directory: /Users/adamduren/Workspace/clients/wurtec/wurtec-s3c-avt-elevator
Please check the config directory.
/Users/adamduren/.vscode-server/extensions/graphql.vscode-graphql-0.4.6/out/server/index.js:567
`,Lit=/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/,xit=/\\n/g,Pit=/\n|\r|\r\n/;function E1e(t,e){let r=Boolean(e&&e.debug),n={};return t.toString().split(Pit).forEach(function(i,s){let a=i.match(Lit);if(a!=null){let o=a[1],u=a[2]||"",l=u.length-1,c=u[0]==='"'&&u[l]==='"';u[0]==="'"&&u[l]==="'"||c?(u=u.substring(1,l),c&&(u=u.replace(xit,Oit))):u=u.trim(),n[o]=u}else r&&y1e(`did not match key and value when parsing line ${s+1}: ${i}`)}),n}function kit(t){let e=Dit.resolve(process.cwd(),".env"),r="utf8",n=!1;t&&(t.path!=null&&(e=t.path),t.encoding!=null&&(r=t.encoding),t.debug!=null&&(n=!0));try{let i=E1e(Rit.readFileSync(e,{encoding:r}),{debug:n});return Object.keys(i).forEach(function(s){Object.prototype.hasOwnProperty.call(process.env,s)?n&&y1e(`"${s}" is already defined in \`process.env\` and will not be overwritten`):process.env[s]=i[s]}),{parsed:i}}catch(i){return{error:i}}}FP.exports.config=kit;FP.exports.parse=E1e});var UP=E(za=>{"use strict";var Mit=za&&za.__createBinding||(Object.create?function(t,e,r,n){n===void 0&&(n=r),Object.defineProperty(t,n,{enumerable:!0,get:function(){return e[r]}})}:function(t,e,r,n){n===void 0&&(n=r),t[n]=e[r]}),Fit=za&&za.__setModuleDefault||(Object.create?function(t,e){Object.defineProperty(t,"default",{enumerable:!0,value:e})}:function(t,e){t.default=e}),jit=za&&za.__importStar||function(t){if(t&&t.__esModule)return t;var e={};if(t!=null)for(var r in t)r!=="default"&&Object.prototype.hasOwnProperty.call(t,r)&&Mit(e,t,r);return Fit(e,t),e},v1e=za&&za.__importDefault||function(t){return t&&t.__esModule?t:{default:t}};Object.defineProperty(za,"__esModule",{value:!0});za.MessageProcessor=void 0;var b1e=v1e(iM()),kh=require("fs"),Fo=jit(require("path")),qit=v1e(cq()),dv=q9(),pp=WA(),Git=SY(),Uit=rP(),I1e=W_(),qP=Ct(),Vit=require("os"),Hit=require("util"),Yit=Hit.promisify(kh.writeFile);jP().config();function v0(t){return new pp.Position(t.line,t.character)}var C1e=class{constructor({logger:e,fileExtensions:r,graphqlFileExtensions:n,loadConfigOptions:i,config:s,parser:a,tmpDir:o,connection:u}){var l;this._schemaCacheInit=!1,this._rootPath=process.cwd(),this._connection=u,this._textDocumentCache=new Map,this._isInitialized=!1,this._willShutdown=!1,this._logger=e,this._graphQLConfig=s,this._parser=(c,d)=>(a!=null?a:I1e.parseDocument)(c,d,r,n,this._logger),this._tmpDir=o||Vit.tmpdir(),this._tmpDirBase=Fo.join(this._tmpDir,"graphql-language-service"),this._tmpUriBase=dv.URI.file(this._tmpDirBase).toString(),this._loadConfigOptions=i,i.extensions&&((l=i.extensions)===null||l===void 0?void 0:l.length)>0&&(this._extensions=i.extensions),kh.existsSync(this._tmpDirBase)||b1e.default(this._tmpDirBase)}get connection(){return this._connection}set connection(e){this._connection=e}async handleInitializeRequest(e,r,n){if(!e)throw new Error("`params` argument is required to initialize.");let i={capabilities:{workspaceSymbolProvider:!0,documentSymbolProvider:!0,completionProvider:{resolveProvider:!0,triggerCharacters:[" ",":","$","(","@"]},definitionProvider:!0,textDocumentSync:1,hoverProvider:!0,workspace:{workspaceFolders:{supported:!0,changeNotifications:!0}}}};if(this._rootPath=n?n.trim():e.rootUri||this._rootPath,this._rootPath||this._logger.warn("no rootPath configured in extension or server, defaulting to cwd"),!i)throw new Error("GraphQL Language Server is not initialized.");return this._logger.info(JSON.stringify({type:"usage",messageType:"initialize"})),i}async _updateGraphQLConfig(){var e,r,n,i,s,a;let o=await this._connection.workspace.getConfiguration({section:"graphql-config"}),u=await this._connection.workspace.getConfiguration({section:"vscode-graphql"});(o==null?void 0:o.dotEnvPath)&&jP().config({path:o.dotEnvPath}),this._settings={...o,...u};let l=((r=(e=this._settings)===null||e===void 0?void 0:e.load)===null||r===void 0?void 0:r.rootDir)||this._rootPath;if(this._rootPath=l,this._loadConfigOptions={...Object.keys((i=(n=this._settings)===null||n===void 0?void 0:n.load)!==null&&i!==void 0?i:{}).reduce((c,d)=>{var p;let f=(p=this._settings)===null||p===void 0?void 0:p.load[d];return f==null&&delete c[d],c},(s=this._settings.load)!==null&&s!==void 0?s:{}),rootDir:l},this._graphQLCache=await Uit.getGraphQLCache({parser:this._parser,loadConfigOptions:this._loadConfigOptions}),this._languageService=new Git.GraphQLLanguageService(this._graphQLCache),(a=this._graphQLCache)===null||a===void 0?void 0:a.getGraphQLConfig){let c=this._graphQLCache.getGraphQLConfig();await this._cacheAllProjectFiles(c)}}async handleDidOpenOrSaveNotification(e){var r,n,i;try{if(!this._isInitialized||!this._graphQLCache)if(!this._settings)await this._updateGraphQLConfig(),this._isInitialized=!0;else return null}catch(c){this._logger.warn(c)}if(!e||!e.textDocument)throw new Error("`textDocument` argument is required.");let{textDocument:s}=e,{uri:a}=s,o=[],u=[];if("text"in s&&s.text)u=this._parser(s.text,a),await this._invalidateCache(s,a,u);else{if(["graphql.config","graphqlrc","package.json",(r=this._settings.load)===null||r===void 0?void 0:r.fileName].filter(Boolean).some(p=>{var f;return(f=a.match(p))===null||f===void 0?void 0:f.length}))return this._logger.info("updating graphql config"),this._updateGraphQLConfig(),{uri:a,diagnostics:[]};let d=this._getCachedDocument(s.uri);d&&(u=d.contents)}let l=this._graphQLCache.getProjectForFile(a);return this._isInitialized&&this._graphQLCache&&((i=(n=l.extensions)===null||n===void 0?void 0:n.languageService)===null||i===void 0?void 0:i.enableValidation)!==!1&&(await Promise.all(u.map(async({query:c,range:d})=>{let p=await this._languageService.getDiagnostics(c,a,this._isRelayCompatMode(c));p&&p.length>0&&o.push(...GP(p,c,d))})),this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didOpen",projectName:l&&l.name,fileName:a}))),{uri:a,diagnostics:o}}async handleDidChangeNotification(e){var r,n;if(!this._isInitialized||!this._graphQLCache)return null;if(!e||!e.textDocument||!e.contentChanges||!e.textDocument.uri)throw new Error("`textDocument`, `textDocument.uri`, and `contentChanges` arguments are required.");let i=e.textDocument,s=e.contentChanges,a=s[s.length-1],o=i.uri,u=this._parser(a.text,o);if(await this._invalidateCache(i,o,u),!this._getCachedDocument(o))return null;await this._updateFragmentDefinition(o,u),await this._updateObjectTypeDefinition(o,u);let c=this._graphQLCache.getProjectForFile(o),d=[];return((n=(r=c.extensions)===null||r===void 0?void 0:r.languageService)===null||n===void 0?void 0:n.enableValidation)!==!1&&await Promise.all(u.map(async({query:p,range:f})=>{let A=await this._languageService.getDiagnostics(p,o,this._isRelayCompatMode(p));A&&A.length>0&&d.push(...GP(A,p,f))})),this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didChange",projectName:c&&c.name,fileName:o})),{uri:o,diagnostics:d}}async handleDidChangeConfiguration(e){return await this._updateGraphQLConfig(),this._logger.log(JSON.stringify({type:"usage",messageType:"workspace/didChangeConfiguration"})),{}}handleDidCloseNotification(e){if(!this._isInitialized||!this._graphQLCache)return;if(!e||!e.textDocument)throw new Error("`textDocument` is required.");let n=e.textDocument.uri;this._textDocumentCache.has(n)&&this._textDocumentCache.delete(n);let i=this._graphQLCache.getProjectForFile(n);this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didClose",projectName:i&&i.name,fileName:n}))}handleShutdownRequest(){this._willShutdown=!0}handleExitNotification(){process.exit(this._willShutdown?0:1)}validateDocumentAndPosition(e){if(!e||!e.textDocument||!e.textDocument.uri||!e.position)throw new Error("`textDocument`, `textDocument.uri`, and `position` arguments are required.")}async handleCompletionRequest(e){if(!this._isInitialized||!this._graphQLCache)return[];this.validateDocumentAndPosition(e);let r=e.textDocument,n=e.position,i=this._getCachedDocument(r.uri);if(!i)return[];let s=i.contents.find(c=>{let d=c.range;if(d&&d.containsPosition(v0(n)))return!0});if(!s)return[];let{query:a,range:o}=s;o&&(n.line-=o.start.line);let u=await this._languageService.getAutocompleteSuggestio[Info  - 4:07:41 PM] Connection to server got closed. Server will restart.
[Info  - 4:07:41 PM] The graphql server has stopped running
[Info  - 4:07:41 PM] The graphql server has stopped running
(node:2855) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
6/2/2022, 4:07:41 PM [3] (pid: 2855) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
6/2/2022, 4:07:41 PM [2] (pid: 2855) graphql-language-service-usage-logs: e: GraphQL Config file is not available in the provided config directory: /Users/adamduren/Workspace/clients/wurtec/wurtec-s3c-avt-elevator
Please check the config directory.
/Users/adamduren/.vscode-server/extensions/graphql.vscode-graphql-0.4.6/out/server/index.js:567
`,Lit=/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/,xit=/\\n/g,Pit=/\n|\r|\r\n/;function E1e(t,e){let r=Boolean(e&&e.debug),n={};return t.toString().split(Pit).forEach(function(i,s){let a=i.match(Lit);if(a!=null){let o=a[1],u=a[2]||"",l=u.length-1,c=u[0]==='"'&&u[l]==='"';u[0]==="'"&&u[l]==="'"||c?(u=u.substring(1,l),c&&(u=u.replace(xit,Oit))):u=u.trim(),n[o]=u}else r&&y1e(`did not match key and value when parsing line ${s+1}: ${i}`)}),n}function kit(t){let e=Dit.resolve(process.cwd(),".env"),r="utf8",n=!1;t&&(t.path!=null&&(e=t.path),t.encoding!=null&&(r=t.encoding),t.debug!=null&&(n=!0));try{let i=E1e(Rit.readFileSync(e,{encoding:r}),{debug:n});return Object.keys(i).forEach(function(s){Object.prototype.hasOwnProperty.call(process.env,s)?n&&y1e(`"${s}" is already defined in \`process.env\` and will not be overwritten`):process.env[s]=i[s]}),{parsed:i}}catch(i){return{error:i}}}FP.exports.config=kit;FP.exports.parse=E1e});var UP=E(za=>{"use strict";var Mit=za&&za.__createBinding||(Object.create?function(t,e,r,n){n===void 0&&(n=r),Object.defineProperty(t,n,{enumerable:!0,get:function(){return e[r]}})}:function(t,e,r,n){n===void 0&&(n=r),t[n]=e[r]}),Fit=za&&za.__setModuleDefault||(Object.create?function(t,e){Object.defineProperty(t,"default",{enumerable:!0,value:e})}:function(t,e){t.default=e}),jit=za&&za.__importStar||function(t){if(t&&t.__esModule)return t;var e={};if(t!=null)for(var r in t)r!=="default"&&Object.prototype.hasOwnProperty.call(t,r)&&Mit(e,t,r);return Fit(e,t),e},v1e=za&&za.__importDefault||function(t){return t&&t.__esModule?t:{default:t}};Object.defineProperty(za,"__esModule",{value:!0});za.MessageProcessor=void 0;var b1e=v1e(iM()),kh=require("fs"),Fo=jit(require("path")),qit=v1e(cq()),dv=q9(),pp=WA(),Git=SY(),Uit=rP(),I1e=W_(),qP=Ct(),Vit=require("os"),Hit=require("util"),Yit=Hit.promisify(kh.writeFile);jP().config();function v0(t){return new pp.Position(t.line,t.character)}var C1e=class{constructor({logger:e,fileExtensions:r,graphqlFileExtensions:n,loadConfigOptions:i,config:s,parser:a,tmpDir:o,connection:u}){var l;this._schemaCacheInit=!1,this._rootPath=process.cwd(),this._connection=u,this._textDocumentCache=new Map,this._isInitialized=!1,this._willShutdown=!1,this._logger=e,this._graphQLConfig=s,this._parser=(c,d)=>(a!=null?a:I1e.parseDocument)(c,d,r,n,this._logger),this._tmpDir=o||Vit.tmpdir(),this._tmpDirBase=Fo.join(this._tmpDir,"graphql-language-service"),this._tmpUriBase=dv.URI.file(this._tmpDirBase).toString(),this._loadConfigOptions=i,i.extensions&&((l=i.extensions)===null||l===void 0?void 0:l.length)>0&&(this._extensions=i.extensions),kh.existsSync(this._tmpDirBase)||b1e.default(this._tmpDirBase)}get connection(){return this._connection}set connection(e){this._connection=e}async handleInitializeRequest(e,r,n){if(!e)throw new Error("`params` argument is required to initialize.");let i={capabilities:{workspaceSymbolProvider:!0,documentSymbolProvider:!0,completionProvider:{resolveProvider:!0,triggerCharacters:[" ",":","$","(","@"]},definitionProvider:!0,textDocumentSync:1,hoverProvider:!0,workspace:{workspaceFolders:{supported:!0,changeNotifications:!0}}}};if(this._rootPath=n?n.trim():e.rootUri||this._rootPath,this._rootPath||this._logger.warn("no rootPath configured in extension or server, defaulting to cwd"),!i)throw new Error("GraphQL Language Server is not initialized.");return this._logger.info(JSON.stringify({type:"usage",messageType:"initialize"})),i}async _updateGraphQLConfig(){var e,r,n,i,s,a;let o=await this._connection.workspace.getConfiguration({section:"graphql-config"}),u=await this._connection.workspace.getConfiguration({section:"vscode-graphql"});(o==null?void 0:o.dotEnvPath)&&jP().config({path:o.dotEnvPath}),this._settings={...o,...u};let l=((r=(e=this._settings)===null||e===void 0?void 0:e.load)===null||r===void 0?void 0:r.rootDir)||this._rootPath;if(this._rootPath=l,this._loadConfigOptions={...Object.keys((i=(n=this._settings)===null||n===void 0?void 0:n.load)!==null&&i!==void 0?i:{}).reduce((c,d)=>{var p;let f=(p=this._settings)===null||p===void 0?void 0:p.load[d];return f==null&&delete c[d],c},(s=this._settings.load)!==null&&s!==void 0?s:{}),rootDir:l},this._graphQLCache=await Uit.getGraphQLCache({parser:this._parser,loadConfigOptions:this._loadConfigOptions}),this._languageService=new Git.GraphQLLanguageService(this._graphQLCache),(a=this._graphQLCache)===null||a===void 0?void 0:a.getGraphQLConfig){let c=this._graphQLCache.getGraphQLConfig();await this._cacheAllProjectFiles(c)}}async handleDidOpenOrSaveNotification(e){var r,n,i;try{if(!this._isInitialized||!this._graphQLCache)if(!this._settings)await this._updateGraphQLConfig(),this._isInitialized=!0;else return null}catch(c){this._logger.warn(c)}if(!e||!e.textDocument)throw new Error("`textDocument` argument is required.");let{textDocument:s}=e,{uri:a}=s,o=[],u=[];if("text"in s&&s.text)u=this._parser(s.text,a),await this._invalidateCache(s,a,u);else{if(["graphql.config","graphqlrc","package.json",(r=this._settings.load)===null||r===void 0?void 0:r.fileName].filter(Boolean).some(p=>{var f;return(f=a.match(p))===null||f===void 0?void 0:f.length}))return this._logger.info("updating graphql config"),this._updateGraphQLConfig(),{uri:a,diagnostics:[]};let d=this._getCachedDocument(s.uri);d&&(u=d.contents)}let l=this._graphQLCache.getProjectForFile(a);return this._isInitialized&&this._graphQLCache&&((i=(n=l.extensions)===null||n===void 0?void 0:n.languageService)===null||i===void 0?void 0:i.enableValidation)!==!1&&(await Promise.all(u.map(async({query:c,range:d})=>{let p=await this._languageService.getDiagnostics(c,a,this._isRelayCompatMode(c));p&&p.length>0&&o.push(...GP(p,c,d))})),this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didOpen",projectName:l&&l.name,fileName:a}))),{uri:a,diagnostics:o}}async handleDidChangeNotification(e){var r,n;if(!this._isInitialized||!this._graphQLCache)return null;if(!e||!e.textDocument||!e.contentChanges||!e.textDocument.uri)throw new Error("`textDocument`, `textDocument.uri`, and `contentChanges` arguments are required.");let i=e.textDocument,s=e.contentChanges,a=s[s.length-1],o=i.uri,u=this._parser(a.text,o);if(await this._invalidateCache(i,o,u),!this._getCachedDocument(o))return null;await this._updateFragmentDefinition(o,u),await this._updateObjectTypeDefinition(o,u);let c=this._graphQLCache.getProjectForFile(o),d=[];return((n=(r=c.extensions)===null||r===void 0?void 0:r.languageService)===null||n===void 0?void 0:n.enableValidation)!==!1&&await Promise.all(u.map(async({query:p,range:f})=>{let A=await this._languageService.getDiagnostics(p,o,this._isRelayCompatMode(p));A&&A.length>0&&d.push(...GP(A,p,f))})),this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didChange",projectName:c&&c.name,fileName:o})),{uri:o,diagnostics:d}}async handleDidChangeConfiguration(e){return await this._updateGraphQLConfig(),this._logger.log(JSON.stringify({type:"usage",messageType:"workspace/didChangeConfiguration"})),{}}handleDidCloseNotification(e){if(!this._isInitialized||!this._graphQLCache)return;if(!e||!e.textDocument)throw new Error("`textDocument` is required.");let n=e.textDocument.uri;this._textDocumentCache.has(n)&&this._textDocumentCache.delete(n);let i=this._graphQLCache.getProjectForFile(n);this._logger.log(JSON.stringify({type:"usage",messageType:"textDocument/didClose",projectName:i&&i.name,fileName:n}))}handleShutdownRequest(){this._willShutdown=!0}handleExitNotification(){process.exit(this._willShutdown?0:1)}validateDocumentAndPosition(e){if(!e||!e.textDocument||!e.textDocument.uri||!e.position)throw new Error("`textDocument`, `textDocument.uri`, and `position` arguments are required.")}async handleCompletionRequest(e){if(!this._isInitialized||!this._graphQLCache)return[];this.validateDocumentAndPosition(e);let r=e.textDocument,n=e.position,i=this._getCachedDocument(r.uri);if(!i)return[];let s=i.contents.find(c=>{let d=c.range;if(d&&d.containsPosition(v0(n)))return!0});if(!s)return[];let{query:a,range:o}=s;o&&(n.line-=o.start.line);let u=await this._languageService.getAutocompleteSuggestio[Info  - 4:07:41 PM] Connection to server got closed. Server will restart.
[Info  - 4:07:41 PM] The graphql server has stopped running
[Info  - 4:07:41 PM] The graphql server has stopped running
(node:2897) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
6/2/2022, 4:07:41 PM [3] (pid: 2897) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
6/2/2022, 4:07:42 PM [2] (pid: 2897) graphql-language-service-usage-logs: e: GraphQL Config file is not available in the provided config directory: /Users/adamduren/Workspace/clients/wurtec/wurtec-s3c-avt-elevator
Please check the config directory.
/Users/adamduren/.vscode-server/extensions/graphql.vscode-graphql-0.4.6/out/server/index.js:567
# REPEATS FIVE TIMES
```

**Comment by simon-abbott** [comment]
@GBrachetta @adamduren If you're using the official GraphQL plugin ([this one](https://marketplace.visualstudio.com/items?itemName=graphql.vscode-graphql), _not_ [this one](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode)), then you want to follow this issue: https://github.com/graphql/graphiql/issues/2421.

**Comment by adamduren** [comment]
@simon-abbott great catch, thank you!

**Comment by jalalmanafi** [comment]
> @GBrachetta @adamduren If you're using the official GraphQL plugin ([this one](https://marketplace.visualstudio.com/items?itemName=graphql.vscode-graphql), _not_ [this one](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode)), then you want to follow this issue: [graphql/graphiql#2421](https://github.com/graphql/graphiql/issues/2421).

Still have same problem 
![Screen Shot 2022-06-03 at 10 31 25](https://user-images.githubusercontent.com/53921355/171800050-d3fa3433-b264-4b9c-8d58-a075a65804e4.png)

**Comment by simon-abbott** [comment]
@jalalbmnf That's using the official plugin, _not this one_. You want https://github.com/graphql/graphiql/issues/2421.
